import Header from '@/components/Header';
import { Grid, Container } from '@mui/material';
import { Box } from '@mui/system';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>MailMate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Box container>
<Header />
      <Grid container spacing={2}>
  <Grid item xs={8}>
    {/* Your sidebar content goes here */}
    Sidebar
  </Grid>

  <Grid item xs={4}>
    {/* Your main content goes here */}
    Main Content
  </Grid>
</Grid>
</Box>

    </>
  );
}
