import MainContent from '@/components/MainContentTab/MainContent';
import { Box } from '@mui/system';
import Head from 'next/head';

export default function Home({searchValue}) {

  return (
    <>
      <Head>
        <title>MailMate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Box container='true' sx={{display:'flex', justifyContent:{sm:'flex-end'}}}>

<Box sx={{width:{xl:'84%',lg:'81%',md:'75%',sm:"62%",xs:'100%'}}}>
  <MainContent searchValue={searchValue} />
</Box>
</Box>
    </>
  );
}
